### ISSUE TITLE
Downloading checkpoints for verification of your results

### ISSUE THREAD

**Issue by JohnMe** [wyczzy/StealthDiffusion#2]
Hi, thanks for your code?

Any chance you can upload the checkpoints somewhere else?  Huggingface ?

I can not access baidu without chinese phone number...

Thanks a lot

**Comment by wyczzy** [comment]
Thank you for your attention to our work. I will upload the weights to HuggingFace as soon as possible and will notify you immediately once there is an update.

**Comment by wyczzy** [comment]
You can obtain our model weights from this link: https://huggingface.co/zzy0123/StealthDiffusion/tree/main.

**Comment by JohnMe** [comment]
Thanks a lot! Looking forward to evaluate.
